networks:
    app-network:
      driver: bridge

services:
  app:
    container_name: app
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ../src/:/opt/app
    networks:
      - app-network
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:1.23-alpine
    depends_on:
      - app
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ../src/:/opt/app
    ports:
      - "8080:80"
    networks:
      - app-network
